apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Bird-finder
  description: Search any bird around the world just with a click of picture and power of AI
  labels:
    google.com/custom: custom_label_value
  annotations:
    google.com/service-discovery: artistweb
    circleci.com/project-slug: github/example-org/artist-website
  tags:
    - java
  links:
    - url: http://13.126.59.135/
      title: Admin Dashboard
      icon: dashboard
spec:
  type: website
  lifecycle: production
  owner: vipul kumar
  system: public-websites
