apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Bird-finder
  description: Search any bird around the world just with a click of picture and power of AI.
  labels:
    13.126.59.135/custom: custom_label_value
  annotations:
    13.126.59.135/service-discovery: artistweb
    circleci.com/project-slug: github/example-org/artist-website
  tags:
    - Node
    - React
    - Python
    - Deep Learning
    - AWS EC-2
  links:
    - url: http://13.126.59.135/
      title: Admin Dashboard
      icon: dashboard
spec:
  type: website
  lifecycle: production
  owner: vipul kumar
  system: public-websites
